### ISSUE TITLE
Dashboard panics when settng up LDAP in Tyk Identity Broker

### ISSUE THREAD

**Issue by n2linux** [TykTechnologies/tyk-identity-broker#117]
**Branch/Environment**
- Branch: Master/3.0
- Environment: On-prem

**Describe the bug**
When setting up LDAP, the UserID doesn't get properly populated, which causes a panic in the Dashboard:
 `ObjectIDs must be exactly 12 bytes long (got 0)`
(Full panic log below, other examples in linked support tickets)

**Reproduction steps**
1. Go to Identity Management 
2. Create a new profile using LDAP as the Provider
3. Provider appropriate settings for LDAP
4. See Dashboard panic

**Actual behavior**
Dashboard panics, LDAP doesn't work

**Screenshots/Video**
Panic log with user details removed:

```
Jul 16 11:11:45 api01svil tyk-identity-broker: time="2020-07-16T11:11:45+02:00" level=info msg="User bind successful" prefix="AD AUTH" username=g.xxxxx.mail
Jul 16 11:11:45 api01svil tyk-identity-broker: time="2020-07-16T11:11:45+02:00" level=info msg="Search: starting..." prefix="AD AUTH"
Jul 16 11:11:45 api01svil tyk-identity-broker: time="2020-07-16T11:11:45+02:00" level=info msg="Running LDAP search" DN="ou=users,o=xxxx" Filter="(&(uid=g.xxxxx.mail))" prefix="AD AUTH"
Jul 16 11:11:45 api01svil tyk-identity-broker: time="2020-07-16T11:11:45+02:00" level=info msg="User bind successful" prefix="AD AUTH" username=g.xxxxxx.mail
Jul 16 11:11:45 api01svil tyk-identity-broker: time="2020-07-16T11:11:45+02:00" level=info msg="Single Sign-On nonce created successfully via Dashboard API!" prefix="TYK_API"
Jul 16 11:11:45 api01svil tyk-analytics: time="Jul 16 11:11:45" level=error msg="Failure in user lookup: g.xxxxxx.mail@xxxx.it. Error: 'not found'"
Jul 16 11:11:45 api01svil tyk-analytics: time="Jul 16 11:11:45" level=info msg="Created a new dashboard user. Logging using dashboard user." OrgId={ORG_ID_REMOVED} User's SSO Email="g.xxxx.mail@xxxx.it"
Jul 16 11:11:45 api01svil tyk-analytics: time="Jul 16 11:11:45" level=error msg="Update failed for user"
Jul 16 11:11:45 api01svil tyk-analytics: time="Jul 16 11:11:45" level=error msg="ObjectIDs must be exactly 12 bytes long (got 0)"
Jul 16 11:11:45 api01svil tyk-analytics: time="Jul 16 11:11:45" level=error msg="Could not update LastLoginDate for dashboard user" userID="ObjectIdHex("")"
Jul 16 11:11:45 api01svil tyk-analytics: ERROR 2020/07/16 11:11:45.276451 panic_handler.go:26: PANIC
Jul 16 11:11:45 api01svil tyk-analytics: URL: /
Jul 16 11:11:45 api01svil tyk-analytics: ERROR: assignment to entry in nil map
Jul 16 11:11:45 api01svil tyk-analytics: STACK:
Jul 16 11:11:45 api01svil tyk-analytics: goroutine 656 [running]:
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).handlePanic(0xc000666270, 0xc0003a9440, 0xc0003a9460, 0x15e2e60, 0x1ed50d0)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:277 +0x508
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*Router).ServeHTTP.func1(0xc000666270, 0xc0003a9440)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:43 +0x6f
Jul 16 11:11:45 api01svil tyk-analytics: panic(0x15e2e60, 0x1ed50d0)
Jul 16 11:11:45 api01svil tyk-analytics: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.(*User).Permissions(0xc000a8e6c0, 0x0, 0x0, 0x0)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/model_user.go:168 +0x33c
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.(*Context).createViewAllowance(0xc000010378, 0xc0000103a8, 0x180c376)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/api_context_methods.go:126 +0x51
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.(*Context).ShowIndex(0xc000010378, 0x1f31dc0, 0xc0003a9440, 0xc0003a9460)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/api_context_methods.go:410 +0x114e
Jul 16 11:11:45 api01svil tyk-analytics: reflect.Value.call(0x1592760, 0x1b7d7d0, 0x13, 0x17fe905, 0x4, 0xc0001b1fe0, 0x3, 0x3, 0x0, 0xc0001b1e98, ...)
Jul 16 11:11:45 api01svil tyk-analytics: /usr/local/go/src/reflect/value.go:447 +0x461
Jul 16 11:11:45 api01svil tyk-analytics: reflect.Value.Call(0x1592760, 0x1b7d7d0, 0x13, 0xc0001b1fe0, 0x3, 0x3, 0xc00034cf40, 0x20, 0x40)
Jul 16 11:11:45 api01svil tyk-analytics: /usr/local/go/src/reflect/value.go:308 +0xa4
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x1f31dc0, 0xc0003a9440, 0xc0003a9460)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:139 +0x396
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.GoCraftHttphandlerFunc.func1(0x1f11a60, 0xc0003a9440, 0xc000caa800)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/server.go:620 +0x40
Jul 16 11:11:45 api01svil tyk-analytics: net/http.HandlerFunc.ServeHTTP(0xc0004b4e70, 0x1f11a60, 0xc0003a9440, 0xc000caa800)
Jul 16 11:11:45 api01svil tyk-analytics: /usr/local/go/src/net/http/server.go:1995 +0x44
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).handleSuccess(...)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:180
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf.(*CSRFHandler).ServeHTTP(0xc0001b22b0, 0x1f11a60, 0xc0003a9440, 0xc000caa800)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/TykTechnologies/nosurf/handler.go:137 +0x587
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.CSRFMiddleware(0x1f31dc0, 0xc0003a9440, 0xc0003a9460, 0xc0003f8810)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/server.go:641 +0x2e9
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc000694540, 0x17601e0, 0xc000010378, 0x16, 0x1f31dc0, 0xc0003a9440, 0xc0003a9460, 0xc0003f8810)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:157 +0x374
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x1f31dc0, 0xc0003a9440, 0xc0003a9460)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/dashboard.DisableCacheMiddleware(0x1f31dc0, 0xc0003a9440, 0xc0003a9460, 0xc0003f8810)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/dashboard/server.go:665 +0xa00
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.(*middlewareHandler).invoke(0xc000663ec0, 0x17601e0, 0xc000010378, 0x16, 0x1f31dc0, 0xc0003a9440, 0xc0003a9460, 0xc0003f8810)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:157 +0x374
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web.middlewareStack.func1(0x1f31dc0, 0xc0003a9440, 0xc0003a9460)
Jul 16 11:11:45 api01svil tyk-analytics: /src/github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/web/router_serve.go:148 +0x17f
Jul 16 11:11:45 api01svil tyk-analytics: github.com/TykTechnologies/tyk-analytics/vendor/github.com/gocraft/
```

**Additional context**
Reported by customers in tickets [10849](https://tyksupport.zendesk.com/agent/tickets/10849), [10879](https://tyksupport.zendesk.com/agent/tickets/10879), and [10890](https://tyksupport.zendesk.com/agent/tickets/10890)

**Comment by n2linux** [comment]
@ilijabojanovic pointed out that there is already a [Dashboard bug](https://github.com/TykTechnologies/tyk-analytics/issues/1617) opened on this. Closing this issue and will move discussion to the other one.
